const products = [
  { 
    _id: '1',
    name: 'iPhone 14 Pro Max',
    image: '/images/iPhone 14 Pro Max.jpg',
    description: 'The latest iPhone with A16 Bionic chip and ProMotion display.',
    brand: 'Apple',
    category: 'Smartphones',
    price: 1099.99,
    countInStock: 50,
    rating: 4.8,
    numReviews: 1200,
  },
  {
    _id: '2',
    name: 'Samsung Galaxy S23 Ultra',
    image: '/images/Samsung Galaxy S23 Ultra.jpg',
    description: 'Samsung\'s flagship phone with a stunning camera and display.',
    brand: 'Samsung',
    category: 'Smartphones',
    price: 1199.99,
    countInStock: 30,
    rating: 4.7,
    numReviews: 800,
  },
  {
        _id: '3',
        name: 'Google Pixel 7 Pro',
        image: '/images/Google Pixel 7 Pro.jpg',
        description: 'Experience the best of Google with the Pixel 7 Pro.',
        brand: 'Google',
        category: 'Smartphones',
        price: 899.99,
        countInStock: 40,
        rating: 4.6,
        numReviews: 600,
     },
    {
        _id: '4',
        name: 'OnePlus 11',
        image: '/images/OnePlus 11.jpg',
        description: 'Fast and smooth performance with the OnePlus 11.',
        brand: 'OnePlus',
        category: 'Smartphones',
        price: 749.99,
        countInStock: 20,
        rating: 4.5,
        numReviews: 500,
    },
    {
        _id: '5',
        name: 'Xiaomi 13 Pro',
        image: '/images/Xiaomi 13 Pro.jpg',
        description: 'Flagship performance with a competitive price.',
        brand: 'Xiaomi',
        category: 'Smartphones',
        price: 899.99,
        countInStock: 25,
        rating: 4.4,
        numReviews: 450,
    },
    {
        _id: '6',
        name: 'Sony Xperia 1 IV',
        image: '/images/Sony Xperia 1 IV.jpg',
        description: 'A multimedia powerhouse with a stunning 4K display.',
        brand: 'Sony',
        category: 'Smartphones',
        price: 1299.99,
        countInStock: 15,
        rating: 4.3,
        numReviews: 300,
    },
]
export default products;